"""add paper bets and leg model_prob

Revision ID: 1dc54d5bb248
Revises: fdb14bf55a9c
Create Date: 2026-07-14 13:25:44.302476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc54d5bb248'
down_revision: Union[str, None] = 'fdb14bf55a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_legs', sa.Column('model_prob', sa.Float(), nullable=True))
    op.add_column('bets', sa.Column('is_paper', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'is_paper')
    op.drop_column('bet_legs', 'model_prob')
    # ### end Alembic commands ###
