"""add game_id player_id market to bet_legs

Revision ID: 7161fe789272
Revises: d3c84dadd674
Create Date: 2026-08-13 14:51:38.982662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7161fe789272'
down_revision: Union[str, None] = 'd3c84dadd674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_legs', sa.Column('game_id', sa.Integer(), nullable=True))
    op.add_column('bet_legs', sa.Column('player_id', sa.Integer(), nullable=True))
    op.add_column('bet_legs', sa.Column('market', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_legs', 'market')
    op.drop_column('bet_legs', 'player_id')
    op.drop_column('bet_legs', 'game_id')
    # ### end Alembic commands ###
