"""add month to alerts

Revision ID: 8721ae3d534d
Revises: ea18be0e7170
Create Date: 2026-07-11 07:22:02.341629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8721ae3d534d'
down_revision: Union[str, None] = 'ea18be0e7170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('month', sa.Date(), nullable=False))
    op.create_unique_constraint('uq_alert_category_month_threshold', 'alerts', ['category_id', 'month', 'threshold_pct'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_alert_category_month_threshold', 'alerts', type_='unique')
    op.drop_column('alerts', 'month')
    # ### end Alembic commands ###
