"""initial schema

Revision ID: b37b14ce87fd
Revises: 
Create Date: 2026-07-11 06:40:40.719884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b37b14ce87fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

bet_type_enum = postgresql.ENUM('single', 'parlay', name='bet_type', create_type=False)
bet_status_enum = postgresql.ENUM(
    'pending', 'won', 'lost', 'push', 'cashed_out', name='bet_status', create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    bet_type_enum.create(bind, checkfirst=True)
    bet_status_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook', sa.String(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bet_type', bet_type_enum, nullable=False),
    sa.Column('stake', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('potential_payout', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', bet_status_enum, nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('net_result', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('bet_id', name=op.f('pk_bets'))
    )
    op.create_index(op.f('ix_bets_sportsbook'), 'bets', ['sportsbook'], unique=False)
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_betting_category', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('plaid_items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_plaid_items'))
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sa.String(), nullable=False),
    sa.Column('plaid_account_id', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('mask', sa.String(length=4), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.item_id'], name=op.f('fk_accounts_plaid_item_id_plaid_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('plaid_account_id', name=op.f('uq_accounts_plaid_account_id'))
    )
    op.create_index(op.f('ix_accounts_plaid_item_id'), 'accounts', ['plaid_item_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('threshold_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_alerts_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_category_id'), 'alerts', ['category_id'], unique=False)
    op.create_table('bet_legs',
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=True),
    sa.Column('line_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('odds', sa.Integer(), nullable=True),
    sa.Column('leg_status', bet_status_enum, nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.bet_id'], name=op.f('fk_bet_legs_bet_id_bets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leg_id', name=op.f('pk_bet_legs'))
    )
    op.create_index(op.f('ix_bet_legs_bet_id'), 'bet_legs', ['bet_id'], unique=False)
    op.create_table('budget_periods',
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_budget_periods_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('period_id', name=op.f('pk_budget_periods')),
    sa.UniqueConstraint('category_id', 'month', name='uq_budget_period_category_month')
    )
    op.create_index(op.f('ix_budget_periods_category_id'), 'budget_periods', ['category_id'], unique=False)
    op.create_table('transactions',
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('plaid_category', sa.String(), nullable=True),
    sa.Column('custom_category', sa.String(), nullable=True),
    sa.Column('is_betting', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('txn_id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('plaid_transaction_id', name=op.f('uq_transactions_plaid_transaction_id'))
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_is_betting'), 'transactions', ['is_betting'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_is_betting'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_budget_periods_category_id'), table_name='budget_periods')
    op.drop_table('budget_periods')
    op.drop_index(op.f('ix_bet_legs_bet_id'), table_name='bet_legs')
    op.drop_table('bet_legs')
    op.drop_index(op.f('ix_alerts_category_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_accounts_plaid_item_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('plaid_items')
    op.drop_table('categories')
    op.drop_index(op.f('ix_bets_sportsbook'), table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###

    bind = op.get_bind()
    bet_status_enum.drop(bind, checkfirst=True)
    bet_type_enum.drop(bind, checkfirst=True)
