"""add external_ref to bets

Revision ID: d3c84dadd674
Revises: 1dc54d5bb248
Create Date: 2026-07-15 10:48:57.688059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c84dadd674'
down_revision: Union[str, None] = '1dc54d5bb248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('external_ref', sa.String(), nullable=True))
    op.create_index(op.f('ix_bets_external_ref'), 'bets', ['external_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_external_ref'), table_name='bets')
    op.drop_column('bets', 'external_ref')
    # ### end Alembic commands ###
