"""add plaid item sync cursor

Revision ID: ea18be0e7170
Revises: b37b14ce87fd
Create Date: 2026-07-11 06:47:31.016995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea18be0e7170'
down_revision: Union[str, None] = 'b37b14ce87fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_items', sa.Column('cursor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_items', 'cursor')
    # ### end Alembic commands ###
