"""add credit card rewards tracker

Revision ID: fdb14bf55a9c
Revises: 8721ae3d534d
Create Date: 2026-07-11 07:34:51.650605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fdb14bf55a9c'
down_revision: Union[str, None] = '8721ae3d534d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

cap_period_enum = postgresql.ENUM('quarterly', 'annual', name='cap_period', create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    cap_period_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('linked_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.account_id'], name=op.f('fk_credit_cards_linked_account_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('card_id', name=op.f('pk_credit_cards')),
    sa.UniqueConstraint('linked_account_id', name=op.f('uq_credit_cards_linked_account_id'))
    )
    op.create_table('card_reward_progress',
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount_spent_at_bonus_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.card_id'], name=op.f('fk_card_reward_progress_card_id_credit_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_card_reward_progress_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id', name=op.f('pk_card_reward_progress')),
    sa.UniqueConstraint('card_id', 'category_id', 'period_start', name='uq_reward_progress_card_category_period')
    )
    op.create_index(op.f('ix_card_reward_progress_card_id'), 'card_reward_progress', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_reward_progress_category_id'), 'card_reward_progress', ['category_id'], unique=False)
    op.create_table('card_reward_rates',
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cap_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cap_period', cap_period_enum, nullable=True),
    sa.Column('effective_start', sa.Date(), nullable=False),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['credit_cards.card_id'], name=op.f('fk_card_reward_rates_card_id_credit_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], name=op.f('fk_card_reward_rates_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rate_id', name=op.f('pk_card_reward_rates'))
    )
    op.create_index(op.f('ix_card_reward_rates_card_id'), 'card_reward_rates', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_reward_rates_category_id'), 'card_reward_rates', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_reward_rates_category_id'), table_name='card_reward_rates')
    op.drop_index(op.f('ix_card_reward_rates_card_id'), table_name='card_reward_rates')
    op.drop_table('card_reward_rates')
    op.drop_index(op.f('ix_card_reward_progress_category_id'), table_name='card_reward_progress')
    op.drop_index(op.f('ix_card_reward_progress_card_id'), table_name='card_reward_progress')
    op.drop_table('card_reward_progress')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###

    bind = op.get_bind()
    cap_period_enum.drop(bind, checkfirst=True)
